name = Furhateyetracking
mainclass = furhatos.app.eyetracking.EyetrackingSkill
language = en
logLevel = INFO
version = 1.0.0
requiresVersion = false
requiresCamera = false
requiresSpeaker = false
requiresMicrophone = false
requiresRecognizer = false
